### ISSUE TITLE
Error while running script

### ISSUE THREAD

**Issue by Erisfiregamer1** [ThioJoe/Windows-Super-God-Mode#1]
I tried to run the script and this error was thrown, causing the script to instantly close:

```Created task link shortcut for File History - Restore your files with File History
Get-LocalizedString : Failed to load library: C:\WINDOWS\diagnostics\system\Keyboard\DiagPackage.dll
At C:\Users\Eris\Downloads\Super_God_Mode.ps1:2119 char:31
+ ... scription = Get-LocalizedString $content.SettingInformation.Descripti ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-LocalizedString
 
Get-LocalizedString : Failed to load library: C:\WINDOWS\diagnostics\system\Keyboard\DiagPackage.dll
At C:\Users\Eris\Downloads\Super_God_Mode.ps1:2129 char:45
+ ... hKeywords = Get-LocalizedString $content.SettingInformation.HighKeywo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-LocalizedString
 
Get-AllSettings-Data : Error parsing MS Settings XML: Cannot set "Description" because only strings can be 
used as values to set XmlNode properties.
At C:\Users\Eris\Downloads\Super_God_Mode.ps1:3294 char:21
+ ... pLinkData = Get-AllSettings-Data -xmlFilePath $allSettingsXmlPath -Sa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-AllSettings-Data```

**Comment by ThioJoe** [comment]
Hm odd. What version of windows are you on? If you type `winver` into the start menu it should give you the exact build number.

Also would you be able to try running it with the -Debug flag and post what it says? The Get-LocalizedString function is one of the more complicated functions

**Comment by Erisfiregamer1** [comment]
Version 23H2 (OS Build 22361.4037)

I will try running the script with -Debug tomorrow, thank you for helping!

**Comment by Strappazzon** [comment]
Windows 10 IoT Enterprise LTSC version 21H2 build 19044.4780
PowerShell version 7.4.5

```ps1
.\Super_God_Mode.ps1 -Debug

Get-LocalizedString : Failed to load library: C:\Windows\System32\WorkFoldersControl.dll
At C:\Users\s9n\Downloads\Super_God_Mode.ps1:2139 char:31
+ ... scription = Get-LocalizedString $content.SettingInformation.Descripti ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-LocalizedString

Get-AllSettings-Data : Error parsing MS Settings XML: Cannot set "Description" because only strings can be used as
values to set XmlNode properties.
At C:\Users\s9n\Downloads\Super_God_Mode.ps1:3557 char:21
+ ... pLinkData = Get-AllSettings-Data -xmlFilePath $allSettingsXmlPath -Sa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-AllSettings-Data
```

![screenshot](https://github.com/user-attachments/assets/0d33a58f-daaf-4301-a04c-d4cfe6425267)

**Comment by coolcoolcat-1** [comment]
uncheck deep links

**Comment by me-dog** [comment]
Getting some of the same. Windows 10 22H2 Build 19045.4780. The first DLL exists, the second doesn't.

> Get-LocalizedString : Failed to load string resource: 110 from C:\Program Files (x86)\Microsoft Office\root\VFS\ProgramFilesX64\Microsoft Office\Office16\MAPISHELL.DLL
> At Super_God_Mode.ps1:1317 char:29
> + ... olvedName = Get-LocalizedString -StringReference $defaultName -Custom ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-LocalizedString

> Get-LocalizedString : Failed to load library: C:\WINDOWS\System32\srchadmin.dll
> At Super_God_Mode.ps1:2153 char:31
> + ... scription = Get-LocalizedString $content.SettingInformation.Descripti ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-LocalizedString

Then there's the 3rd error, almost the same as OP but at a different line number:

> 
> Get-AllSettings-Data : Error parsing MS Settings XML: Cannot set "Description" because only strings can be used as values to set XmlNode properties.
> At Super_God_Mode.ps1:3588 char:21
> + ... pLinkData = Get-AllSettings-Data -xmlFilePath $allSettingsXmlPath -Sa ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-AllSettings-Data

This interrupts execution for good. Debug log attached.

[debug.txt](https://github.com/user-attachments/files/16764393/debug.txt)

**Comment by ThioJoe** [comment]
Let me know if this still occurrs but it should be fully fixed as of 1.2.0. The problem was basically the tasks XML file in windows refers to some files that are not in certain versions like ARM or IoT apparently. The script should no longer crash or throw the errors in these cases.

**Comment by me-dog** [comment]
The script now runs to completion, so the fix did something right. :-) Still getting a few warnings but I guess that's inevitable with something this complex:

> WARNING: Failed to load string resource, no result returned for: 110 from C:\Program Files (x86)\Microsoft Office\root\VFS\ProgramFilesX64\Microsoft Office\Office16\MAPISHELL.DLL
> WARNING: Failed to load library during typical string reference lookup: C:\WINDOWS\System32\srchadmin.dll
> WARNING: Failed to load library during typical string reference lookup: C:\WINDOWS\diagnostics\system\Search\DiagPackage.dll
> WARNING: Failed to load library during typical string reference lookup: C:\WINDOWS\diagnostics\system\Search\DiagPackage.dll
> WARNING: Failed to load library during typical string reference lookup: C:\WINDOWS\System32\WorkFoldersControl.dll

**Comment by me-dog** [comment]
More info: the script leves behind a shortcut after the second warning above:

UnresolvedReference - @%SystemRoot%_System32_srchadmin.dll,-601#immutable1

The shortcut doesn't work but has this target:

C:\WINDOWS\system32\control.exe /name Microsoft.IndexingOptions

![Capture](https://github.com/user-attachments/assets/75a354e4-2270-4e2a-8b21-85ad408f05df)

srchadmin.dll does not exist on my system.

**Comment by ThioJoe** [comment]
All systems have the same xml file but not all have the same actual files so inevitably some of the references might not work. So it's not a problem.
