### ISSUE TITLE
Out of Memory Error

### ISSUE THREAD

**Issue by Evgeen** [ThioJoe/Windows-Super-God-Mode#14]
Script tried to scan big files of NoxVM drives and failed into out of memory error.

![image](https://github.com/user-attachments/assets/9c2b33dd-d548-49b7-9bd5-ba0cc7d2ef27)

**Comment by EDM115** [comment]
Maybe adding a check of Available memory left - size of the current processed file > 0 would avoid such errors from being thrown

**Comment by ThioJoe** [comment]
Yea I'm working on some optimizations. I assume this was with the deeper scan option enabled?

**Comment by Evgeen** [comment]
> I assume this was with the deeper scan option enabled?

Yeah, it was

**Comment by EDM115** [comment]
> Yea I'm working on some optimizations. I assume this was with the deeper scan option enabled?

indeed

**Comment by ThioJoe** [comment]
Closing as fixed in the new 1.2.0 release
