### ISSUE TITLE
The property '(default)' cannot be found on this object

### ISSUE THREAD

**Issue by IanBAdams** [ThioJoe/Windows-Super-God-Mode#17]
Hi, I’m getting the following error while running the script using both Windows PowerShell and PowerShell 7.4.4.:
> .\Super_God_Mode.ps1

Use the GUI window that just appeared to select any options and run the script.

Beginning script execution...

----- Processing 162 Shell Folders -----
The property '(default)' cannot be found on this object. Verify that the property exists.
At C:\Users\IanAd\downloads\Super_God_Mode.ps1:1310 char:5
+     $defaultName = (Get-ItemProperty -Path $defaultPath -ErrorAction  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

Reran using -verbose which gave the following:
> .\Super_God_Mode.ps1 -verbose

Use the GUI window that just appeared to select any options and run the script.

Beginning script execution...

----- Processing 162 Shell Folders -----
VERBOSE: Processing CLSID: {00020D75-0000-0000-C000-000000000046}
VERBOSE: Attempting to get folder name for CLSID: {00020D75-0000-0000-C000-000000000046}
VERBOSE: Checking default value at: Registry::HKEY_CLASSES_ROOT\CLSID\{00020D75-0000-0000-C000-000000000046}
The property '(default)' cannot be found on this object. Verify that the property exists.
At C:\Users\IanAd\downloads\Super_God_Mode.ps1:1310 char:5
+     $defaultName = (Get-ItemProperty -Path $defaultPath -ErrorAction  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

I've included a screenshot of the registry entry below.
![Screenshot 2024-08-27 113059](https://github.com/user-attachments/assets/13b31e52-2437-441b-b88b-649e329df925)

Google says the CLSID is related to Outlook desktop icon. I have Outlook installed but don’t have a desktop icon (I like my desktop uncluttered).

I know a bit of powershell so could probably butcher your script to get it to work on my system but thought it better to raise with you in case others have the same kind of issue.

Any thoughts?

**Comment by ThioJoe** [comment]
It shouldn't produce an error for that line (that's what SilentlyContinue is for) especially since the default value indeed is not set. Do you have some special setting enabled on powershell? From what i've googled, might be related to 'Strict Mode' or something not sure. Either way I don't think this is actually a problem, there are many keys where there is no default value set.
