### ISSUE TITLE
MsResource Error

### ISSUE THREAD

**Issue by HerbJul** [ThioJoe/Windows-Super-God-Mode#2]
I discovered a second error when executing the script

Get-MsResource :    > All attempts to retrieve resource failed for ms-resource:                                         @{windows?ms-resource://Windows.UI.SettingsAppThreshold/SearchResources/SettingsPageSignInOptions/HighKeywords}. Error  code: -2147024774                                                                                                       In C:\Users\19jul\Downloads\Super_God_Mode.ps1:1070 Zeichen:16                                                          +         return Get-MsResource $StringReference                                                                        +                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                            + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException                                          + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-MsResource

**Comment by ThioJoe** [comment]
Yea I probably have to make the function that handles that part a bit more robust, it is a pretty complicated one.

**Comment by ThioJoe** [comment]
Should be fixed for next actual release or you can try the current build here: https://github.com/ThioJoe/Windows-Super-God-Mode/blob/main/Super_God_Mode.ps1
