### ISSUE TITLE
Can't run script Windows 11

### ISSUE THREAD

**Issue by StarDroid5000** [ThioJoe/Windows-Super-God-Mode#21]
When i open the launcher it starts spitting out errors and closes.

Here are te errors i was getting:

PS C:\Users\CurrentUser\Downloads> .\Super_God_Mode.ps1

Use the GUI window that just appeared to select any options and run the script.

Add-Type : Cannot add type. Definition of new types is not supported in this language mode.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:235 char:5
+     Add-Type -AssemblyName PresentationFramework
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Add-Type], PSNotSupportedException
    + FullyQualifiedErrorId : CannotDefineNewType,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : Cannot add type. Definition of new types is not supported in this language mode.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:236 char:5
+     Add-Type -AssemblyName System.Windows.Forms
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Add-Type], PSNotSupportedException
    + FullyQualifiedErrorId : CannotDefineNewType,Microsoft.PowerShell.Commands.AddTypeCommand

New-Object : Cannot create type. Only core types are supported in this language mode.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:507 char:15
+     $reader = New-Object System.Xml.XmlNodeReader $xaml
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [New-Object], PSNotSupportedException
    + FullyQualifiedErrorId : CannotCreateTypeConstrainedLanguage,Microsoft.PowerShell.Commands.NewObjectCommand

Unable to find type [Windows.Markup.XamlReader].
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:508 char:15
+     $window = [Windows.Markup.XamlReader]::Load($reader)
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Windows.Markup.XamlReader:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:511 char:5
+     $chkDontGroupTasks = $window.FindName("chkDontGroupTasks")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:512 char:5
+     $chkUseAlternativeCategoryNames = $window.FindName("chkUseAlterna ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:513 char:5
+     $chkAllURLProtocols = $window.FindName("chkAllURLProtocols")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:514 char:5
+     $chkCollectExtraURLProtocolInfo = $window.FindName("chkCollectExt ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:515 char:5
+     $chkKeepPreviousOutputFolders = $window.FindName("chkKeepPrevious ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:516 char:5
+     $chkAllowDuplicateDeepLinks = $window.FindName("chkAllowDuplicate ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:517 char:5
+     $chkDeepScanHiddenLinks = $window.FindName("chkDeepScanHiddenLink ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:520 char:5
+     $chkCollectStatistics = $window.FindName("chkCollectStatistics")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:521 char:5
+     $chkCollectCLSID = $window.FindName("chkCollectCLSID")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:522 char:5
+     $chkCollectNamedFolders = $window.FindName("chkCollectNamedFolder ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:523 char:5
+     $chkCollectTaskLinks = $window.FindName("chkCollectTaskLinks")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:524 char:5
+     $chkCollectMSSettings = $window.FindName("chkCollectMSSettings")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:525 char:5
+     $chkCollectDeepLinks = $window.FindName("chkCollectDeepLinks")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:526 char:5
+     $chkCollectURLProtocols = $window.FindName("chkCollectURLProtocol ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:527 char:5
+     $chkCollectAppxLinks = $window.FindName("chkCollectAppxLinks")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:530 char:5
+     $txtOutputPath = $window.FindName("txtOutputPath")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:531 char:5
+     $txtCurrentPath = $window.FindName("txtCurrentPath")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:532 char:5
+     $txtOutputFolderName = $window.FindName("txtOutputFolderName")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:533 char:5
+     $btnBrowse = $window.FindName("btnBrowse")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:534 char:5
+     $btnOK = $window.FindName("btnOK")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:537 char:5
+     $cmbLoggingLevel = $window.FindName("cmbLoggingLevel")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

The property 'SelectedIndex' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:544 char:9
+         $cmbLoggingLevel.SelectedIndex = 0
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'Text' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:549 char:5
+     $txtOutputPath.Text = $defaultOutputPath
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'Text' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:550 char:5
+     $txtOutputFolderName.Text = $defaultOutputFolderName
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

Cannot invoke method. Method invocation is supported only on core types in this language mode.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:551 char:5
+     $txtCurrentPath.Text = [System.IO.Path]::Combine($defaultOutputPa ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:554 char:5
+     $btnBrowse.Add_Click({
+     ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:570 char:5
+     $chkCollectURLProtocols.Add_Checked({
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:574 char:5
+     $chkCollectURLProtocols.Add_Unchecked({
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

The property 'IsEnabled' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:580 char:5
+     $chkCollectAppxLinks.IsEnabled = $chkCollectURLProtocols.IsChecke ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:582 char:5
+     $txtOutputPath.Add_TextChanged({ UpdateCurrentPath })
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:583 char:5
+     $txtOutputFolderName.Add_TextChanged({ UpdateCurrentPath })
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:586 char:5
+     $btnAbout = $window.FindName("btnAbout")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:587 char:5
+     $btnAbout.Add_Click({
+     ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:612 char:5
+     $btnOK.Add_Click({
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\CurrentUser\Downloads\Super_God_Mode.ps1:617 char:5
+     $result = $window.ShowDialog()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Script GUI window appears to have been closed. Exiting script.

**Comment by ThioJoe** [comment]
Did you ever create an environment variable called `__PSLockDownPolicy` ? That could do it too. I have a video where I talk about that here: https://youtu.be/zW69MisrsWk?t=142

From my knowledge there are 3 main ways constrained language mode might be enabled:
* Having any AppLocker script rules set up
* Having the  `__PSLockDownPolicy` environment variable set
* Having a Windows Defender Application Control policy set up (Also Smart App Control enabled, which uses WDAC)

**Comment by StarDroid5000** [comment]
I forgot that i created the __PSLockdownPolicy variable. thx

**Comment by ThioJoe** [comment]
Ok great, closing this. I've added a wiki page with frequently asked questions like this which i'll update going forward.
