### ISSUE TITLE
Script not signed 

### ISSUE THREAD

**Issue by DenDx** [ThioJoe/Windows-Super-God-Mode#24]
.\super_god_mode.ps1
Super_God_Mode.ps1 is not digitally signed. You cannot run this script

**Comment by ThioJoe** [comment]
The release versions attached to each release are signed, not every single commit version.

<img width="367" alt="image" src="https://github.com/user-attachments/assets/64260390-4744-4cc0-b3e2-7735cacc8057">

**Comment by DenDx** [comment]
Got this baby purrin' Super-software. Thanks for what you do. 8)
