### ISSUE TITLE
[Error]: Script running restricted

### ISSUE THREAD

**Issue by JimMcl610** [ThioJoe/Windows-Super-God-Mode#29]
### Not a Duplicate Issue

- [x] I have searched the existing issues and confirmed this is not a duplicate.

### Script Stops Early or Doesn't Run  (If applicable)

Script runs for a bit then crashes / stops early

### Script Finishes But With a Problem (If applicable)

Not applicable

### What happened?

My machine Policy is restricted and I cannot seem to change it. 

This is what PS returns when I try and set policy:

PS C:\sgm> Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
Set-ExecutionPolicy : Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective 
execution policy of Restricted. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".
At line:1 char:1
+ Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], SecurityException
    + FullyQualifiedErrorId : ExecutionPolicyOverride,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand

PS C:\sgm> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy      Restricted
   UserPolicy       Undefined
      Process          Bypass
  CurrentUser       AllSigned
 LocalMachine    Unrestricted

If I try and use your BAT file I see the PS terminal flash open and then close.  Nothing else happens.  The above is when trying to run it manually.

### Script Version

GUI doesn't load but just downloaded ver 1.2.2

### Steps or conditions to reproduce

1. 
2. 
3. 

### Windows Version

Windows 11

### How did you run the script?

Command Line Only (Using -NoGUI)

### Error Output

```shell
PS C:\sgm> Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
Set-ExecutionPolicy : Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective 
execution policy of Restricted. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".
```

### Screenshots

![image](https://github.com/user-attachments/assets/3bfb1e7a-bb97-4d16-ac52-5d39fde78cfc)

**Comment by ThioJoe** [comment]
At someone you must have set a group policy setting for that. See this section of my video where I talk about changing it: https://youtu.be/zW69MisrsWk?t=341

**Comment by JimMcl610** [comment]
This has not made any differnece. 
In the Policy editor this is the setting
![image](https://github.com/user-attachments/assets/e407f60a-0c52-481c-9a40-84bbc3a07aec)
 But in PS I still get 
![image](https://github.com/user-attachments/assets/1b591cfc-002b-4fc3-b04b-b06a5d77ce1e)

**Comment by ThioJoe** [comment]
A few things I can think of. First make sure you close the powershell window and re-open it for it to take effect. 

Also make sure the policy is set like this:

<img width="1102" alt="image" src="https://github.com/user-attachments/assets/24a3abbf-1016-46ed-a955-ddfa801c9092">

**Comment by JimMcl610** [comment]
Tried all that. Still the same. Very frustrating.
![image](https://github.com/user-attachments/assets/93ac1051-f37f-4d74-abd4-93bc78d161f0)

**Comment by JimMcl610** [comment]
Having looked at the video you linked again I just realised I have Win 11 Home but I also have the Group Policy Editor started by typing gpedit.msc in the comand line!  Is that even possible.  I'm not using PolicyPlus to make these changes.  Is it possible the the Group Policy Editor is running but not making/saving changes because I have Win Home?

**Comment by ThioJoe** [comment]
Oh yea that's probably the reason. Group Policy Editor does not actually work on Windows Home edition even if you can get it running - changing the settings with it simply has no effect. 

You must have changed it some other way, or something did for you at some point. Is your computer managed by a company or something?

You might also be able to change it in the registry, not sure if it will stick like that either. It would be in:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\PowerShell as "ExecutionPolicy"
