### ISSUE TITLE
[Bug]: Windows 11 LTSC Insider Preview Dev Channel got some errors

### ISSUE THREAD

**Issue by enessmr** [ThioJoe/Windows-Super-God-Mode#31]
### Not a Duplicate Issue

- [X] I have searched the existing issues and confirmed this is not a duplicate.

### Script Stops Early or Doesn't Run  (If applicable)

Not applicable

### Script Finishes But With a Problem (If applicable)

Script finishes, but a problem occurs while searching for links

### What happened?

![{B081FA2D-ADBD-49CF-8B40-7D10D23CD94B}](https://github.com/user-attachments/assets/557da81e-b4d6-4445-b0cd-c722e1185ae2)

### Script Version

Latest

### Steps or conditions to reproduce

1.  open the cmd in admin
2.  copy the ps1 file to system32
3.  open cmd in admin again
4.  errors

### Windows Version

Windows 11

### How did you run the script?

GUI via launcher batch file

### Additional Context

System:
MSI B450M-A PRO MAX
AMD Ryzen 5 3600
GTX 1060 3GB by ZOTAC
(uh oh! cmd crasshed in 20:33 in turkey!)
240GB ssd (windows)
1TB hdd for other things such as backup, video games etc.
250GB hdd for arch linux

### Screenshots

already in the what happened

**Comment by ThioJoe** [comment]
It's not actually a problem, some directories just can't be searched. Also don't run the file from your system directory, there's no reason to do that

**Comment by enessmr** [comment]
thanks joe! :)
Well well well... LTSC is extremely small like Tiny11
![{DAAE1814-7815-4D86-A476-493C54C75464}](https://github.com/user-attachments/assets/bf4900db-c62a-4451-ad7a-26170fc36c34)
![{3E3B5CA4-5086-405F-B652-D5A0C5443E8F}](https://github.com/user-attachments/assets/07113d8b-4cc9-4eff-9755-b963a00b5856)
Some tools are outdated. (In LTSC.)
