### ISSUE TITLE
[Bug]: WARNING loading resource strings...

### ISSUE THREAD

**Issue by ArtClark** [ThioJoe/Windows-Super-God-Mode#34]
### Not a Duplicate Issue

- [ ] I have searched the existing issues and confirmed this is not a duplicate.

### Checked the Frequently Asked Questions Page

- [ ] I checked the [FAQ page](https://github.com/ThioJoe/Windows-Super-God-Mode/wiki/Frequently-Asked-Questions) on the wiki with solutions to common issues.

### Script Stops Early or Doesn't Run  (If applicable)

Not applicable

### Script Finishes But With a Problem (If applicable)

Script finishes, but a problem occurs while searching for links

### What happened?

Created CLSID Shortcut For: Credential Manager
WARNING: Failed to load string resource, no result returned for: 110 from C:\Program Files (x86)\Microsoft
Office\root\VFS\ProgramFilesX64\Microsoft Office\Office16\MAPISHELL.DLL
Created CLSID Shortcut For: @C:\Program Files (x86)\Microsoft Office\root\VFS\ProgramFilesX64\Microsoft Office\Office16\MAPISHELL.DLL,-110
Created CLSID Shortcut For: Install New Programs
C

### Script Version

1.2.2

### Steps or conditions to reproduce

1. run bat
2. observed warning
3. bat and script run to completion
4. Great work, keep up the great tools.

### Windows Version

Windows 10

### How did you run the script?

GUI via launcher batch file

**Comment by ThioJoe** [comment]
It's not a problem, for some reason they have a reference to a DLL that doesn't exist on all computers. Mine gives that same warning.

The technical explanation is it do be like that sometimes
