### ISSUE TITLE
需要完整文件吗？Need full documentation?

### ISSUE THREAD

**Issue by YanYiGe2023** [ThioJoe/Windows-Super-God-Mode#35]
I just need Super_God_Mode.ps1 and SuperGodMode-EasyLauncher.bat Or do you need to download the whole zip file of the version? Because I noticed that there are also powershell script files in the Extra Tools folder, can the program still work without them？ 

我只需要Super_God_Mode.ps1和SuperGodMode-EasyLauncher.bat 还是需要下载版本的整个zip文件？ 因为我注意到Extra Tools文件夹中也有powershell脚本文件，缺失它们程序还可以工作吗？

**Comment by ThioJoe** [comment]
I already answered your same question two weeks ago: https://github.com/ThioJoe/Windows-Super-God-Mode/discussions/30#discussioncomment-10513488

**Comment by YanYiGe2023** [comment]
> 两周前我已经回答了你同样的问题：[#30 （评论）](https://github.com/ThioJoe/Windows-Super-God-Mode/discussions/30#discussioncomment-10513488)

不好意思，我还以为我没有问过
Sorry, I thought I hadn't asked
