### ISSUE TITLE
Don't Work

### ISSUE THREAD

**Issue by AHMED-RUSHDI-CODE** [ThioJoe/Windows-Super-God-Mode#6]

**Comment by CinnaBonZone** [comment]
How does it not work for you

**Comment by AHMED-RUSHDI-CODE** [comment]
Must Run It With Visual Studio Code

How to Open It & Work
https://github.com/user-attachments/assets/d84a15b8-c4b7-4208-857b-ca3668e9241e

Process 
https://github.com/user-attachments/assets/a4038c8d-56ea-4c27-b222-21e563fdceb3

Result !!
![Screenshot 2024-08-25 222738](https://github.com/user-attachments/assets/7cb6531f-a8af-406d-81f2-1efdde965f14)

Thank You For Your Time !!
And Thanks TheoJoe .. Great Job !!
