### ISSUE TITLE
it won't run

### ISSUE THREAD

**Issue by LeonMiszkurka** [ThioJoe/Windows-Super-God-Mode#7]
it won't run

**Comment by jgh07** [comment]
If you want us to help you, you will need to provide some more information...

**Comment by ThioJoe** [comment]
Without any more info I can only assume it's a skill issue

**Comment by LeonMiszkurka** [comment]
when I download it and then click on the super god mode it dose not run

**Comment by LeonMiszkurka** [comment]
https://github.com/user-attachments/assets/ea7ec887-1ccb-428b-b053-3590e4de2013

**Comment by ThioJoe** [comment]
Yea you also need the .ps1 file which is the actual script, you only downloaded the launcher file
